name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Angular Application
        # Replace [repository-name] with your actual GitHub repository name in your project settings.
        # e.g., --base-href /MSG/
        run: |
          npx ng build --configuration production --base-href /${{ github.event.repository.name }}/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/app/browser # Build folder for Angular 21 client assets
          branch: gh-pages # The branch the action will deploy to
          clean: true
